### ISSUE TITLE
As a PO, I can split an unfinished story, so that the team can continue work in the next sprint

### ISSUE THREAD

**Issue by 51ngul4r1ty** [51ngul4r1ty/atoll-core#222]
**Acceptance Criteria**

- [x] 1. UI should allow user to easily split a story that hasn't been accepted in the current (or previous) sprint.
- [x] ~~2. UI should calculate remaining percentage based tasks completed (when available- if not done before this story has been completed this should be split out to a different story).~~ - N/A (yet)
- [ ] 3. UI should allow user to enter percentage of story completed in last sprint (i.e. override value calculated above).
- [ ] 4. UI should calculate "used points" and "remaining points" based on this percentage.
- [ ] 5. UI should allow user to override the "remaining points" (and calculate "used points" and "percentage remaining" based on the change).
- [x] ~~6. UI should give the user the choice of keeping the remaining work in the product backlog or placing it in the next sprint (the default).~~ - N/A (yet)
- [x] 7. UI should show "split x of y" for the split backlog items in each sprint.
- [ ] 8. UI should show used/remaining story points on backlog item card.
- [x] 9. UI should show "x of y unallocated splits" in the product backlog to handle multiple backlog item parts that are in the product backlog.
- [x] 10. Related to the AC above, moving multiple backlog item parts to the product backlog for the same backlog item is permitted but should not result in the parts being joined.  The user will be able to do this intentionally, but it should not happen automatically.
- [ ] 11. Related to AC `#1` changing the status on the story part in the newest sprint will update the story status to whatever status this part has (because this is the final part so it dictates the full story status).
- [ ] 12. Related to AC `#1` changing the status on the story part in an older sprint (when other part/s are in a newer sprint) will not update the story status unless the story status is not "in progress" (if any part is in progress the story itself is in progress).

**Technical Notes**

1. To support this story it is necessary to allow a backlog item to be added to more than a single sprint (this will be a fairly heavy lift because it will change a fair bit of existing logic).
2. New fields need to be supported:
  * Sprint Backlog Item will need a new "usedPoints" field (when a story is split both of the splits will have the same
    "usedPoints" value but this could change if the story splits again so the story spans 3 sprints).
  * Previous sprint's "usedSplitPoints" will need to be calculated.
  * Next sprint's "remainingSplitPoints" will need to be calculated.

**Tasks**

- [x] 1. Database design
- [x] 2. UI design
- [x] 3. Refactor app to use new data structure (make sure backlog item view is updated)
- [x] 3.1. Make sure add new story also adds the first story part
- [x] 3.2. Make sure plan view's product backlog item is updated to use new data (after moving first split)
- [x] 3.3. Make sure plan view's sprint backlog item is updated to use new data (after moving)
- [x] 3.4. Make sure plan view's product backlog item isn't removed when moving first split when 2 are in backlog.
- [x] 3.5. Make sure plan view's product backlog item is updated to use new data (after moving second split)
- [x] 3.6. Make sure status updates in a sprint use the sprint item part data (data.extra.sprintStats: { acceptedPoints, plannedPoints, totalPoints })
- [x] 3.7. Make sure it adds a story part to a sprint
- [x] 3.8. Make sure moving second split from sprint into product backlog doesn't error out (currently it does).
- [x] 3.9. Move one out of two parts to sprint backlog leaves PBI in a selected state even though the selection has been reset.
- [x] 3.10. Make sure that it isn't possible to add 2 splits from same story to same sprint (UI can't handle this and it doesn't make sense anyway).
- [x] 4. Add menu item for story splitting
- [ ] 4.1. Make sure menu item for story splitting is disabled if story part is "Accepted" or "Released" (AC `#1`)
- [ ] 4.2. Make sure API call to split story fails if story is in "Accepted" or "Released" status (AC `#1`).
- [ ] 5. Implement story splitting UI (see AC `#2` and AC `#5`)
- [x] 6. Implement story splitting API (include AC `#3` in this)
- [x] 7. Hook up UI and API
- [ ] 8. Make fields editable for AC `#4`
- [ ] 9. Modify backlog item view to include story split details
- [x] 10. Make sure AC `#1` is handled
- [x] 11. Make sure AC `#6` is handled
- [x] 12. Make sure AC `#7` is handled (if it wasn't done in task `#5` above)
- [x] 13. Make sure push notifications are still working (push notifications to notify of splits etc. will be done in another story)
- [x] 14. Make sure that totalParts field is updated (it seems to be 1 currently for everything)
- [ ] 15. Make sure editing split story in product backlog preserves story estimate vs points remaining.
- [ ] 16. Ensure that backlogItemPutHandler does the right thing when story estimate is updated when parts of the story are in existing sprints.  Need to think this through.
- [ ] 17. Switch over all respondWithItem calls to use respondWithObj and buildResponseWithItem.
- [x] 18. Make sure that checking a split item in the backlog doesn't change the split remaining points (seems there's a bug where it changes `gh-227` with 4/5 in the backlog to 5/5 after checking the box in preparation of adding it to a sprint)
- [x] 19. Make sure that moving a backlog item part to the product backlog sets sprint status such that it can receive a part of this story again.
- [x] 20. Make sure that moving a product backlog item into a sprint sets sprint status such that it can't receive a part of this story again.

**Database Design**

![image](https://user-images.githubusercontent.com/41717340/117549859-c1a66080-b00a-11eb-8755-ed0c4ee94bc6.png)

https://dbdiagram.io/d/60929f37b29a09603d13808b

**UI Design**

*_Product Backlog Item_*
![image](https://user-images.githubusercontent.com/41717340/117666513-ecf78f80-b171-11eb-9d4c-e912c9fed3bd.png)

*_Sprint Backlog Item_*
![image](https://user-images.githubusercontent.com/41717340/117666741-2e883a80-b172-11eb-9ffe-4ce1b40646d8.png)

**Bugs/Todo**

1. Moving a part out of a sprint back to the product backlog, then returning it to the sprint doesn't show it as a split backlog item until you refresh.
2. Splitting story when there's no future sprint results in a failure that doesn't mean anything to a user.
3. Create work item to deal with this: ApiBacklogItemInSprint has a estimate and storyEstimate fields... but the database names are different so this needs refactoring.

**Screenshots of End Result**
![image](https://user-images.githubusercontent.com/41717340/119353290-b4c37700-bc70-11eb-93c9-1f4740808fb8.png)

**Example**

* Story A estimated at 13 points - starts off as a complete story in Sprint 1.
* Story A isn't completed at end of Sprint 1 but team thinks they need need 5 points to complete it, so it has to be split into 2 parts:
  - Sprint 1 has Story A Part 1 with 13 estimated points (at story level) and 8 used points (5 remaining).
  - Sprint 2 now has Story A Part 2 in it with 13 estimated points (at story level) and 5 estimated points at part level.
* At the end of Sprint 2 the story still isn't complete.  The team acknowledges there was more work than they thought, even at the start of Sprint 2.  They think 8 points will be enough though.
  - Sprint 1 status remains unchanged.
  - Sprint 2 has Story A Part 2 with 13 estimated points (at story level) and -3 used points because the total story points needs to add up to 13 (used total + remaining points = 13 points).  Used points is now calculated as 8 - 3 = 5.
  - Sprint 3 now has Story A Part 3 in it with 13 estimated points (at story level) and 8 estimated points at part level.
* At end end of Sprint 3 the story is completed:
  - Sprint 1 and 2 status remains unchanged.
  - Sprint 3 has Story A Part 3 with 13 estimated points (at story level) and 8 used points.
